### ISSUE TITLE
Default values are not being applied properly by the NPM package

### ISSUE THREAD

**Issue by joe-denea** [treasure-data/td-js-sdk#110]
if **`config.pathname`** and **`config.host`** are not set in the NPM package version of the SDK, they show up in the resultant URL as `%40HOST` and `@pathname`, rather than the actual default values.

**Comment by castor4bit** [comment]
I have also encountered a similar problem.
`@HOST` and `@PATHNAME` can be specified at initialization, but `@VERSION` cannot.

**Comment by MikeMcElroy** [comment]
Hi @joe-denea and @castor4bit, this should have been resolved in version 1.9.2 and beyond.  Please make sure you've upgraded and let us know if there continues to be a problem
