### ISSUE TITLE
Question: is there a xamarin compatible td sdk.

### ISSUE THREAD

**Issue by BenjaminDev** [treasure-data/td-js-sdk#164]
https://dotnet.microsoft.com/apps/xamarin

in particular a xamarin native app as apposed to xamarin.Forms app.

**Comment by toru-takahashi** [comment]
Hello,

Unfortunately, we haven't considered supporting Xamarin by this JS SDK.
I'm sorry that I'm not familiar with Xamarin thus we have no confidence if this works or not with Xamarin

Thanks,

**Comment by toru-takahashi** [comment]
Hi, btw,
You can contact Treasure Data Support (support@treasure-data.com) If you are a Treasure Data Customer.

**Comment by BenjaminDev** [comment]
I'll close this for now as I have asked support. Thanks
