### ISSUE TITLE
td-js-sdk doesn't get os version info for Windows 10

### ISSUE THREAD

**Issue by ryutaroy** [treasure-data/td-js-sdk#26]
For windows 7, 8, 8.1 environment, we can see version in td_os(not td_os_version).
But we cannot see any version info in windows 10.
In windows10, td_os -> 'Windows' and  td_os_version -> null.
Sorry for just reporting.

![screen shot 2016-05-17 at 18 11 03](https://cloud.githubusercontent.com/assets/773318/15317221/8801dbc2-1c5b-11e6-919f-081b4b13a115.png)

**Comment by toru-takahashi** [comment]
Our js-sdk backend server uses [uap-ruby](https://github.com/ua-parser/uap-ruby) v2.1.5.
It doesn't support Windows10.
```
[
  %q|Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/42.0.2311.135 Safari/537.36 Edge/12.10240|,
].each do |ua|
  p UserAgentParser.parse(ua).os.to_s
end
=> "Windows"
```

`user_agent_parser:2.3.0` can detect it but it's terribly slower than 2.1.5. 
We might need to add raw useragent column for js sdk...

**Comment by cesarandreu** [comment]
I'm adding `td_user_agent` in the next release: https://github.com/treasure-data/td-js-sdk/pull/28

And you can use the TD_PARSE_AGENT UDF:
https://docs.treasuredata.com/articles/presto-udfs#tdparseagent
