### ISSUE TITLE
td_client_id produces weird null values 

### ISSUE THREAD

**Issue by xerial** [treasure-data/td-js-sdk#6]
I found the following null values (\00, shown as `^@`) appended to td_client_id values:
```
 xxxxxxxxx-d7c4-4ce7-f6ad-b67e3cebf9fe^@^@^@^@
 xxxxxxxxx-d7c4-4ce7-f6ad-b67e3cebf9fe^@^@^@^@^@
 ...
```

**Comment by tmaiaroto** [comment]
Well, given the source code has the comment: ```// Maybe look into a more legit solution later``` ... I'm going to assume it's not real compatible across various browsers and that it really wasn't a high priority to someone here.

I might suggest: https://github.com/makeable/uuid-v4.js ...or perhaps a time-UUID package.
